### PR TITLE
Fix: UNABLE to load uWSGI plugin: ./carbon_plugin.so

### PR DESCRIPTION
**Pull request by pellaeon**
Fix issue #210

### CODE REVIEW

**Comment by DennisBP** [comment]
:+1:

**Comment by cwjohnston** [comment]
Hi @pellaeon, @DennisBP !

Can you please provide some additional detail around this fix (e.g. specific platforms where you encounter the error)? It does not seem to work for this cookbook's  `centos-64` Test Kitchen suite.

**Comment by DennisBP** [comment]
I just changed the ```node['graphite']['install_type]``` from ```source``` to ```package``` to fix this error.

**Comment by MiguelPF** [comment]
+1 in ubuntu 12.04 this fix the  "!!! UNABLE to load uWSGI plugin: ./carbon_plugin.so: cannot open shared object file: No such file or directory !!!" problem

**Comment by slyness** [comment]
This will break things like Centos where that plugin directory will likely be in `/usr/lib64/uwsgi`

However, This is an issue. We're going to resolve this with a different PR. /cc @tas50

**Pull request closed without merging**
