### PR TITLE
Allow storage schema and config sorting to be optional

### LINKED ISSUE #218: Ordering of graphite_storage_schema
I'm trying to create two storage schemas. The problem is that they are always written to the conf file in the same order, no matter how I order them in the cookbook. It always writes the "catchall" schema first so all other definitions which follow are ignored (since catch all always matches the stat pattern)

This is what I'm trying to do 
```ruby
graphite_storage_schema "stats" do
  config ({
    pattern: "^stats.",
    retentions: "5s:6h,1min:7d,10min:5y"
  })
end

graphite_storage_schema "catchall" do
  config ({
    pattern: "^.*",
    retentions: "5s:6h,1min:7d,10min:5y"
  })
end
```
And the output file is always (even when I change the order in the recipe):
```
      +# This file is managed by Chef, your changes *will* be overwritten!
      +
      +[catchall]
      +PATTERN = ^.*
      +RETENTIONS = 60:100800,900:63000
      +
      +[stats]
      +PATTERN = ^stats.
      +RETENTIONS = 5s:6h,1min:7d,10min:5y
```

How can I force order of schemas into the file?

Thanks!

### PR DESCRIPTION
**Pull request by jonlives**
This pull request adds attributes to allow storage schema and config sorting to be optionally disabled. Both attributes default to true, which preserves the current default behaviour.

If either attribute is set to false, storage schema and config resources will be written to the accumulator file in the order they occur in the recipe.

This fixes #218.

### CODE REVIEW

**Comment by webframp** [comment]
I like this much better, thanks! I'll try to merge asap

**Comment by webframp** [comment]
Default behavior remains the same and this makes it more flexible for users writing wrappers. Seems safe to merge, thanks!

**Comment by jonlives** [comment]
@webframp any idea when a new version might make it up to the supermarket?

**Comment by webframp** [comment]
@jonlives I've been traveling, sorry for delayed response. I'll take a look at the state of things and see about prepping a point release for this coming week

**Pull request merged**
